export const actionTypes = {
  FETCH_WEATHER_DATA_START: "FETCH_WEATHER_DATA_START",
  FETCH_WEATHER_DATA_ERROR: "FETCH_WEATHER_DATA_ERROR",
  FETCH_WEATHER_DATA_SUCCESS: "FETCH_WEATHER_DATA_SUCCESS",
  GET_GEOLOCATION_DATA_SUCCESS: "GET_GEOLOCATION_DATA_SUCCESS",
  GET_GEOLOCATION_DATA_ERROR: "GET_GEOLOCATION_DATA_ERROR",
  GET_GEOLOCATION_DATA_START: "GET_GEOLOCATION_DATA_START"
};
